# fly.toml app configuration file generated for shader-llm on 2025-02-02T21:03:32+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shader-llm'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  VITE_API_URL = "https://shader-llm-api.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
